<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_idcbr.sitih</name>
   <tag></tag>
   <elementGuidId>814a4b2a-78dd-4ef0-a7ab-f8c825f6cdf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-detail']/div/div/div[4]/div[4]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.user-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;idcbr.sitih&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b75a116e-8f6e-40f8-b23a-7ad095f6c3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-name</value>
      <webElementGuid>fd93bb2e-6147-4873-8de3-989a6ee84b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>idcbr.sitih</value>
      <webElementGuid>f6585e9b-1759-4e1b-a81b-3a32c3fac232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>idcbr.sitih</value>
      <webElementGuid>2c81529b-858b-46ec-b58a-abeb409323d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-detail&quot;)/div[@class=&quot;main-page&quot;]/div[@class=&quot;header_box&quot;]/div[@class=&quot;personal_info keyboard-focus&quot;]/div[@class=&quot;e_banner_right&quot;]/div[@class=&quot;system-setting keyboard-focus&quot;]/div[@class=&quot;user-name&quot;]</value>
      <webElementGuid>dfd6d07c-9920-4a5f-bba0-fa7138aeee71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-detail']/div/div/div[4]/div[4]/div/div[2]</value>
      <webElementGuid>6b53232e-4d60-4b51-8f07-ccbbd48cb3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Other Tabs'])[1]/following::div[13]</value>
      <webElementGuid>1096bd4a-8389-4fbf-b021-1449ebacc5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close All Tabs'])[1]/following::div[13]</value>
      <webElementGuid>6a87db80-f374-4105-85d4-180ff80da9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Favorites'])[1]/preceding::div[97]</value>
      <webElementGuid>6f1acfcd-dfdb-4404-b067-a5346a2bb3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales Order (SO)'])[1]/preceding::div[99]</value>
      <webElementGuid>beb35f4a-3e41-4698-81ca-87b4b0617248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='idcbr.sitih']/parent::*</value>
      <webElementGuid>3cd7db16-969d-4f7f-a7a0-a49d028e87b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/div[2]</value>
      <webElementGuid>6ec3b70f-3fb9-4b04-bcff-c7d7ea529b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'idcbr.sitih' and (text() = 'idcbr.sitih' or . = 'idcbr.sitih')]</value>
      <webElementGuid>825aefe3-d2f2-465a-847d-b79829e4014b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
