<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Inbound Leads_1718629549775</name>
   <tag></tag>
   <elementGuidId>8aa0e7cd-4771-4ec9-8f21-d64da10ff77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ky851168370</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ky851168370']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\31 718629549775&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8691f59f-6a9d-4e78-93d6-b0c505a8529b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ky851168370</value>
      <webElementGuid>52354aab-5562-4a37-ad06-486b578b9ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ows-frame-panel</value>
      <webElementGuid>49c23ff9-dfae-4a1f-a8a8-3faacd8e92a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>beb4d0aa-0690-46d1-921f-f99cbb821ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3938ecea-ccf9-42c1-8d29-44c79a8a2f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1718629549775</value>
      <webElementGuid>80eb376b-4344-470e-8aca-2957a1e08b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app/standalone/index1.html#/spl2/xl_lead_mgmt/xlm_leads_menu</value>
      <webElementGuid>04bb6797-4a45-4da0-acd2-ef610358c05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6dfe4c61-9b69-4cc5-ac5b-a3e894d540c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ky851168370&quot;)</value>
      <webElementGuid>814da5fc-522c-451d-8331-8207b87f24b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ky851168370']</value>
      <webElementGuid>1d7e0391-da0c-441d-8a9d-ab70afa1be9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-ky851168370']/div/iframe</value>
      <webElementGuid>4f7d3a30-fb53-43a7-9341-ad32b39a635a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/iframe</value>
      <webElementGuid>1d5a7977-81b6-4af7-b083-b04604e1c4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ky851168370' and @name = '1718629549775' and @src = '/app/standalone/index1.html#/spl2/xl_lead_mgmt/xlm_leads_menu']</value>
      <webElementGuid>a9c1e1c8-96a2-4b68-a818-43a22e6d7797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
