<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Report</name>
   <tag></tag>
   <elementGuidId>5c1f1fb7-13ca-4e96-8ed2-8ba556012c43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title=&quot;Report&quot; and @class=&quot;level-2 link-nav&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sub_source</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91e9cf2d-9ba7-4eac-ad72-f3fad36bb82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d339b07-9e4b-4798-ad77-90a7ee850a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>5fda7fb1-3e45-4804-a995-c4bbf61f183d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nftype</name>
      <type>Main</type>
      <value>Nf.form.SingleSelect</value>
      <webElementGuid>ae015a5f-0fd9-4557-8fbf-265ccd08b9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hiddenname</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>1793179e-5fb9-4f77-bc10-cd7e4a38026b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_avoididduplicated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b43947b-dfc4-4c2d-a536-a0d0ec03ab84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>querybean</name>
      <type>Main</type>
      <value>pageBaseInstanceQueryer</value>
      <webElementGuid>6732649a-6a07-4014-ad59-17144d8e4b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>windowbean</name>
      <type>Main</type>
      <value>pageBaseWindowBuilder</value>
      <webElementGuid>d01fd0fc-1fdc-4d58-b343-53ada209dd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>{&quot;valueField&quot;:&quot;sub_source_data&quot;,&quot;modelName&quot;:&quot;/xl_lead_mgmt/xl_lead_mgmt/xlm_source_sub_source&quot;,&quot;displayField&quot;:&quot;sub_source_data&quot;}</value>
      <webElementGuid>ed429f28-ae69-41b1-9ef1-211819600d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>sub_source_data</value>
      <webElementGuid>6f95f203-ab2e-4b40-903e-413ae8fa9f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>b846d7ce-4567-4296-b2d2-e6d185dcbd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowwidth</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>296deb1e-b6eb-4bf6-bc29-94cc04afd2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showsearchwin</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29628c57-9bdb-4a0e-af4f-b003b27286ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>627714c1-8b71-4a78-85f4-42e3845d1dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>d621b36c-bb21-45f4-a448-2a40b165de10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text x-form-field single-select</value>
      <webElementGuid>d463b0b7-ba1b-4661-9741-d3d21331a80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_source&quot;)</value>
      <webElementGuid>3902e8f5-beb8-4260-916c-2f7a0f955ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sub_source']</value>
      <webElementGuid>219111cd-1f25-47f8-8394-1ffc1476f5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen7']/input[2]</value>
      <webElementGuid>466accf0-1c5a-40eb-a428-0ffa9554a537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/div/input[2]</value>
      <webElementGuid>6b7e6e6c-e8b4-4879-af0b-2c5a09e5ae7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub_source' and @placeholder = '-Select-']</value>
      <webElementGuid>4d09feb3-ab8d-4b8f-92ec-33d666752acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
