<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create_Inbound</name>
   <tag></tag>
   <elementGuidId>c579aab6-cd29-4b2e-8289-d314cb9672b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='createBt']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sub_source</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>babe1171-11ed-4bf6-aa7b-7baa631b2118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73fd5bc3-557c-4ede-9358-235e3decb4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>4121de58-8575-4c38-8c52-a9eea55a9ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nftype</name>
      <type>Main</type>
      <value>Nf.form.SingleSelect</value>
      <webElementGuid>198249be-5135-4f14-8fd5-91665ededf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hiddenname</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>30c6448a-8f3d-47b4-a494-d6fa6b0c133d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_avoididduplicated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9085591d-3b46-41c7-bd76-feb748724e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>querybean</name>
      <type>Main</type>
      <value>pageBaseInstanceQueryer</value>
      <webElementGuid>c3b6d4fe-67e9-4324-b8fd-928c8f4c6e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>windowbean</name>
      <type>Main</type>
      <value>pageBaseWindowBuilder</value>
      <webElementGuid>610a521d-9938-421c-a6e6-da73e99f9cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>{&quot;valueField&quot;:&quot;sub_source_data&quot;,&quot;modelName&quot;:&quot;/xl_lead_mgmt/xl_lead_mgmt/xlm_source_sub_source&quot;,&quot;displayField&quot;:&quot;sub_source_data&quot;}</value>
      <webElementGuid>bdb522e1-e3a9-4dc2-a528-6db55521f565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>sub_source_data</value>
      <webElementGuid>bd4b6dbf-c7bb-459b-a0d4-014565b7541f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2cf0034b-f7a3-46a8-9ddb-342ee9e24dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowwidth</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>3e630ff0-bf2a-4453-9e57-3113b69ba683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showsearchwin</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88cc6b48-7bdc-4640-965e-86ab767de8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03bb7190-b773-414f-804b-1fd682ac08fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>a0ea75eb-b83c-405a-89a3-10a79522dce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text x-form-field single-select</value>
      <webElementGuid>520aecd1-d1b0-4372-b4a1-1eb63b2214f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_source&quot;)</value>
      <webElementGuid>0ce3136b-8371-43d2-bf50-67ca8aafa4c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sub_source']</value>
      <webElementGuid>ed0db1d9-79e0-4561-8216-08057a7620aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen7']/input[2]</value>
      <webElementGuid>eed9eb25-3e5b-4d33-a66e-5fa33edaa9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/div/input[2]</value>
      <webElementGuid>1e501516-9d83-44d8-826a-7ab19411d4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub_source' and @placeholder = '-Select-']</value>
      <webElementGuid>7429cafc-b039-4d47-8a96-e944bae7d242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
