<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Outbound</name>
   <tag></tag>
   <elementGuidId>1335d121-b083-4d85-94e5-074d7d62b5bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title=&quot;Outbound Leads&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sub_source</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f453abf5-ee04-488b-981b-6c4b4b380c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18affba3-e305-476c-a984-41670bdd824f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>bdc6e275-5c4c-46a5-a67d-0f98f391ceb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nftype</name>
      <type>Main</type>
      <value>Nf.form.SingleSelect</value>
      <webElementGuid>f055d0e6-57ef-405c-ab0f-450e09edf37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hiddenname</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>c0b94559-46b2-4814-a60d-009fc184182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_avoididduplicated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a8b64ac-c4b7-4de5-8d36-1f71b8ab0b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>querybean</name>
      <type>Main</type>
      <value>pageBaseInstanceQueryer</value>
      <webElementGuid>d2d2e183-7fee-40c3-8de9-925531de22f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>windowbean</name>
      <type>Main</type>
      <value>pageBaseWindowBuilder</value>
      <webElementGuid>473b6f8b-d81b-4962-af0e-2db3f46c7dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>{&quot;valueField&quot;:&quot;sub_source_data&quot;,&quot;modelName&quot;:&quot;/xl_lead_mgmt/xl_lead_mgmt/xlm_source_sub_source&quot;,&quot;displayField&quot;:&quot;sub_source_data&quot;}</value>
      <webElementGuid>2f06fa65-a491-4bb7-95b3-f2b12f4d4a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>sub_source_data</value>
      <webElementGuid>06aad414-5f99-4477-9c92-55320a8a622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>c61940a9-343c-415d-b837-ae0ea20abccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowwidth</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>33a4b035-e403-414b-a6dc-b7779d21fc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showsearchwin</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02c4867d-7fb8-4cb7-af3c-48a1a870885c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>73022e70-3848-46bf-85c5-8cc9c68d983c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>340c2af1-687d-4807-aa54-7efadf7896ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text x-form-field single-select</value>
      <webElementGuid>98506386-eed4-4aa4-bcb4-9d3e396d3b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_source&quot;)</value>
      <webElementGuid>b2a9985e-888a-4803-b67c-9a139c5cdae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sub_source']</value>
      <webElementGuid>1234eaf2-9b92-43db-a903-382055e8d153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen7']/input[2]</value>
      <webElementGuid>a201bbf2-f796-4385-a119-5a0a79c29856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/div/input[2]</value>
      <webElementGuid>719871a9-f6cd-4a82-8bba-29401f50c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub_source' and @placeholder = '-Select-']</value>
      <webElementGuid>a0a0a88b-28fb-4827-a780-746421c6cebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
