<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inbound</name>
   <tag></tag>
   <elementGuidId>1a8d0b53-d10b-4ae1-a7fe-3fee37499645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title=&quot;Inbound Leads&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sub_source</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3054fe7e-f02c-42cc-af17-824aea319532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef208dcb-3a74-4c4f-8d2b-22f96a2f3702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>a1940801-6595-4dd0-88fa-866b4c08a145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nftype</name>
      <type>Main</type>
      <value>Nf.form.SingleSelect</value>
      <webElementGuid>b96877b5-61e4-4802-8f03-aa74b4d17ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hiddenname</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>bd84d521-2b3c-48c0-bf93-eb4af6f7371a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_avoididduplicated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbecab2e-4843-4387-bba4-b5aa17cecea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>querybean</name>
      <type>Main</type>
      <value>pageBaseInstanceQueryer</value>
      <webElementGuid>cf39b4f7-9b1d-4621-b9bc-3e794d0bc503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>windowbean</name>
      <type>Main</type>
      <value>pageBaseWindowBuilder</value>
      <webElementGuid>7900df72-03a7-4d0a-8858-4e410d725697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>{&quot;valueField&quot;:&quot;sub_source_data&quot;,&quot;modelName&quot;:&quot;/xl_lead_mgmt/xl_lead_mgmt/xlm_source_sub_source&quot;,&quot;displayField&quot;:&quot;sub_source_data&quot;}</value>
      <webElementGuid>50a5b06b-1048-40f5-b0d4-7f2302669aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>sub_source_data</value>
      <webElementGuid>2d81ef40-69aa-4929-86ad-71a281f4350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>c99be26b-2b5d-432a-b1c1-b4624e165fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowwidth</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>72bc5438-0a65-4464-b6c9-0deea99a5851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showsearchwin</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9957497a-3c58-4163-a5e4-35d43a4f5758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>daa234f4-e11a-4a78-808c-1f1c1c4ebcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>f3044db9-71f3-49c8-b84c-3bf1b74b0719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text x-form-field single-select</value>
      <webElementGuid>a687f607-4f1b-4275-b721-5ce7481a2ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_source&quot;)</value>
      <webElementGuid>e5d59c99-91b8-4764-8883-f2b09dd62c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sub_source']</value>
      <webElementGuid>dd568b9e-aa2b-42e2-8159-3568bd960650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen7']/input[2]</value>
      <webElementGuid>273f8387-e716-45db-824f-c72813a00ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/div/input[2]</value>
      <webElementGuid>4eb6a0d3-8f43-4c99-ba4c-12086e6c8078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub_source' and @placeholder = '-Select-']</value>
      <webElementGuid>55e9e701-0477-4b66-94d0-baa5a9d07128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
