<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AdminLeadManagement</name>
   <tag></tag>
   <elementGuidId>228291c4-1725-4fe2-b09a-962e8f3eb716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title=&quot;Admin&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sub_source</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sub_source</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb1e94a8-a501-4d89-a15b-d5e945f06c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7578ea4-131b-405b-a755-d1725b7e6eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>90844a52-0d3c-4567-a58b-af5bc4eff312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nftype</name>
      <type>Main</type>
      <value>Nf.form.SingleSelect</value>
      <webElementGuid>3d99b6d5-f674-4367-92af-b98e38fef6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hiddenname</name>
      <type>Main</type>
      <value>sub_source</value>
      <webElementGuid>0eeaf02f-8002-4c12-be8c-06e374abb9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_avoididduplicated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53b05bd7-5f37-44cf-8199-fbb987334e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>querybean</name>
      <type>Main</type>
      <value>pageBaseInstanceQueryer</value>
      <webElementGuid>117ad7d5-3b2d-41e8-b909-4a387db27e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>windowbean</name>
      <type>Main</type>
      <value>pageBaseWindowBuilder</value>
      <webElementGuid>3f9799da-b4df-4087-959d-6b6833e1a79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>{&quot;valueField&quot;:&quot;sub_source_data&quot;,&quot;modelName&quot;:&quot;/xl_lead_mgmt/xl_lead_mgmt/xlm_source_sub_source&quot;,&quot;displayField&quot;:&quot;sub_source_data&quot;}</value>
      <webElementGuid>9fed3fb0-e607-4570-8f7c-65772be88722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayfield</name>
      <type>Main</type>
      <value>sub_source_data</value>
      <webElementGuid>70828dd7-b913-4099-bfec-dc702905ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>491c3a2a-e8d3-448a-b063-27e67454dd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>searchwindowwidth</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>129f0f36-a49c-43aa-a106-59248c07de48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showsearchwin</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f99e6626-7258-4fb5-9f05-30dfc355fe17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44368615-657c-48cc-afa6-723d82fee148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>-Select-</value>
      <webElementGuid>bdbe654c-1a7b-4165-928b-4256647c8515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text x-form-field single-select</value>
      <webElementGuid>0b47a634-b6cf-4983-8304-827199346c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub_source&quot;)</value>
      <webElementGuid>c4b52a67-fb51-4f21-b251-3eaae21788cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sub_source']</value>
      <webElementGuid>f2c39a5c-f571-4608-bc53-27829be825bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ext-gen7']/input[2]</value>
      <webElementGuid>19e1a644-4778-4669-a40b-22f3b25e1e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label/div/input[2]</value>
      <webElementGuid>5a5aa8dd-4939-4a84-a731-b538b1ea2130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sub_source' and @placeholder = '-Select-']</value>
      <webElementGuid>6768e369-80d0-4280-b781-c7165862f17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
