<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_idcbr.sitih_menu-list-top</name>
   <tag></tag>
   <elementGuidId>c7ef04d3-93fb-405c-a8cc-c30cd8d0560b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-list-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menuList']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.menu-list-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd49c901-34b0-4fba-aea6-cc62c885e605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-list-top</value>
      <webElementGuid>03297c2e-1561-4cf4-ab50-117b14c856a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuList&quot;)/div[@class=&quot;menu-list-top&quot;]</value>
      <webElementGuid>b3516a5a-d634-49b4-a85c-56f4ecfe689a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuList']/div</value>
      <webElementGuid>b84de7c2-c9ae-4644-9bbd-1f06b7b709be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='idcbr.sitih'])[1]/following::div[8]</value>
      <webElementGuid>86f203f7-44c6-4718-b200-f0ac2240eddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Other Tabs'])[1]/following::div[21]</value>
      <webElementGuid>981731c0-ac83-4785-9484-a72abd514891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Favorites'])[1]/preceding::div[3]</value>
      <webElementGuid>0787a540-78a4-458f-90b8-d06fa8e8ec7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FTTH'])[1]/preceding::div[6]</value>
      <webElementGuid>20d4e00f-674e-4095-9508-8462222874ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>cdbab6f4-9d89-44cf-874e-9603da2fecd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
