<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sales Order (SO)_1718542680278</name>
   <tag></tag>
   <elementGuidId>fa7da978-cfab-4a6a-be82-530fdc222ad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ky-514231121']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ky-514231121</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\31 718542680278&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f18dcf17-357b-43d2-910f-5bed09a5122d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ky-514231121</value>
      <webElementGuid>50ea2094-12fb-4f0e-abd4-f4abec2d7188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ows-frame-panel</value>
      <webElementGuid>018b10f4-b966-4b29-a855-eb00254d13ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2f1312d1-8fa9-4894-a513-88ee4d527156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f917c410-5e80-4f93-a56f-f804d45736aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1718542680278</value>
      <webElementGuid>6b20bcf4-1996-43fd-bdca-24b01b9a3369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app/spl/xl_home_fiber/xlhome_sales_order_grid2_v4.spl</value>
      <webElementGuid>2c8ce74a-4684-461e-abd8-d606eb5bc610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47395b80-a067-4c92-92a1-aa59805c5402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ky-514231121&quot;)</value>
      <webElementGuid>8521fa66-5ec2-4e3c-8db8-1785ac597ae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ky-514231121']</value>
      <webElementGuid>d578ba95-b908-492f-a6c7-04d0d428a3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-ky-514231121']/div/iframe</value>
      <webElementGuid>4461c30e-809f-4c07-817e-0658a6eaed7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/iframe</value>
      <webElementGuid>d5c2a883-5281-4cc9-bcab-5094f835c6b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ky-514231121' and @name = '1718542680278' and @src = '/app/spl/xl_home_fiber/xlhome_sales_order_grid2_v4.spl']</value>
      <webElementGuid>956ac27d-99cc-4076-9e4b-8687f8562639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
