<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Inbound Leads_1718712312306</name>
   <tag></tag>
   <elementGuidId>b6ecc308-68fd-4dfb-b518-4012e0ed15f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ky851168370']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ky851168370</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\31 718712312306&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cce15fe1-61f3-463d-b946-c24553789f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ky851168370</value>
      <webElementGuid>84081cf5-1f3f-4b1e-9c23-b91e0ecc10ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ows-frame-panel</value>
      <webElementGuid>4c665d9e-3c54-4fc1-89d2-4e019eb90755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5a80c89c-0a58-429e-b30c-58bfea84ccd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b5bdd9ba-8d32-478e-ae5e-b61ed064f70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1718712312306</value>
      <webElementGuid>54f05c23-42d6-4d6a-a98f-f88feef8ffbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app/standalone/index1.html#/spl2/xl_lead_mgmt/xlm_leads_menu</value>
      <webElementGuid>119f2d85-f6d2-4cf7-97a4-5aa5d43fa08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd27eaa0-1849-405f-aac1-955d5293ee95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ky851168370&quot;)</value>
      <webElementGuid>16bdb06c-d444-491e-a3ac-0ff73d01cc11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ky851168370']</value>
      <webElementGuid>09ae8fab-637b-4422-91b7-56da8ba2c5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-ky851168370']/div/iframe</value>
      <webElementGuid>cf08a53a-2ff8-42c1-ad79-aff3a713aff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/iframe</value>
      <webElementGuid>6ed50ab4-576c-4982-b68c-d5e51df2dec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ky851168370' and @name = '1718712312306' and @src = '/app/standalone/index1.html#/spl2/xl_lead_mgmt/xlm_leads_menu']</value>
      <webElementGuid>ae16e156-5fdf-4bd9-b16c-338027173418</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
