<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Leads ID_leads_id</name>
   <tag></tag>
   <elementGuidId>3916ea17-9b8a-48e1-9c19-00e8c9bbc02d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leads_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leads_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#leads_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ff994e-7cc4-4468-84b9-9dbaae48ebbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>679f26aa-fa24-4c36-8733-b6cd1e7617da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leads_id</value>
      <webElementGuid>9decda82-e8c4-4b38-9d2f-9f564b05cc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sdm_input sdm_input_normal sdm_input_164</value>
      <webElementGuid>81837ce6-d181-44f3-be9e-525c396ba085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leads_id</value>
      <webElementGuid>a1b58f52-dcc6-4cce-9873-8c453d66d9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leads_id&quot;)</value>
      <webElementGuid>c4101f59-63dd-4895-bae3-39a96cef3433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_OWS/Lead_Management/Page_OWS/iframe_Inbound Leads_1718712312306</value>
      <webElementGuid>18299231-7bfa-4304-8db5-5085fc623f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leads_id']</value>
      <webElementGuid>03383685-6a66-46bd-859e-a3f57fb6391d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='inbound_tb_grid']/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>ecc85dde-ca6b-415e-9825-2b7a6b342c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9382ee70-4df1-4aa5-9bc4-7afcdbe8abec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'leads_id' and @id = 'leads_id']</value>
      <webElementGuid>0ca65cb1-c14c-49ae-a4ba-f700a9bc3a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
