<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Request Update</name>
   <tag></tag>
   <elementGuidId>2841dc51-02c2-4b20-97be-2408b6f3a3ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div[2]/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;History Balance Cuti Tahunan 07/01/2020 17 day(s)&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32f5d54d-b53c-4e47-9050-7df06f940842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Application/Time/PersonalLeave/IndexPersonalLeaveHistory?employeeLeaveBalanceUID=621190f7-95a5-4f18-8599-796e13dedf06</value>
      <webElementGuid>83099b2f-1513-426d-982d-b16715f5a4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>5c3ec307-5db7-4bc7-a00d-ebe016066ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd30249e-e089-4d8e-9cce-fa6aec11fa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-begin</name>
      <type>Main</type>
      <value>RemovePrevData</value>
      <webElementGuid>b255c801-38d8-493f-8072-fc3b2056000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-mode</name>
      <type>Main</type>
      <value>replace</value>
      <webElementGuid>2dfcd56b-ac45-4de0-9b1e-7db483162215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-update</name>
      <type>Main</type>
      <value>#result</value>
      <webElementGuid>d7fcda62-3dfd-41dd-8679-986f4d55ac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-loading</name>
      <type>Main</type>
      <value>#Loading</value>
      <webElementGuid>89a64574-42a6-470f-8beb-db5d3811f9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>8250e4ab-17c3-4b2e-a585-8281a7f5ef8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[@class=&quot;k-grid-content&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;button-column&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>535487b7-0442-4174-829a-85d3ce2eede6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>c930a53c-f4e0-4f2a-82fc-02e0810928f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'History')]</value>
      <webElementGuid>7512b80a-50d5-490b-8c3b-3aa2ff6b61fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Balance'])[1]/following::a[1]</value>
      <webElementGuid>9f7884c5-5343-461d-8e27-d0a2b1b4475d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Date'])[1]/following::a[3]</value>
      <webElementGuid>245401ea-9de9-434a-a7c1-2d7937efb8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Cuti Tahunan'])[1]/preceding::a[1]</value>
      <webElementGuid>b5866b90-42ea-4225-8333-e7b40e3c3eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[2]/preceding::a[1]</value>
      <webElementGuid>3034942d-3c1e-4cf2-8d83-d3a823ac3a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='History']/parent::*</value>
      <webElementGuid>08fe9ec9-8c60-4983-b0d2-6b3b32fb2618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Application/Time/PersonalLeave/IndexPersonalLeaveHistory?employeeLeaveBalanceUID=621190f7-95a5-4f18-8599-796e13dedf06')]</value>
      <webElementGuid>c3c28e1e-2914-4ae5-9d1f-5625706c8662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>3cbfb532-e2f2-4098-b0c7-ce8f3fea7525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Application/Time/PersonalLeave/IndexPersonalLeaveHistory?employeeLeaveBalanceUID=621190f7-95a5-4f18-8599-796e13dedf06' and (text() = 'History' or . = 'History')]</value>
      <webElementGuid>08c30ffb-fdab-4570-9516-7274e7ba6a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
