<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tunjangan Khusus</name>
   <tag></tag>
   <elementGuidId>6e494bcc-182c-4b91-83f7-67f9c4401282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='5658c99e-a891-4dc4-95e6-c38e4510642b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5658c99e-a891-4dc4-95e6-c38e4510642b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Tunjangan Khusus&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>96215d02-d779-4af3-9701-0b1efc961963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc246772-9e67-43ff-855f-64edb2b3c5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>890c6df8-53df-4532-99d0-da203d4cf222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c461fbd0-1ffe-4376-8f85-ce8dd7537f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-hover</value>
      <webElementGuid>30f64050-8cdc-4f76-a7e8-47de2a5cf3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5504fb5-4df3-484b-a058-fb8203d671db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5658c99e-a891-4dc4-95e6-c38e4510642b</value>
      <webElementGuid>0a4e13c0-4dcc-422c-9e1d-9810f2292e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tunjangan Khusus</value>
      <webElementGuid>d242ea88-ac92-4cbf-9350-6cf5133467dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5658c99e-a891-4dc4-95e6-c38e4510642b&quot;)</value>
      <webElementGuid>89cd02bc-7b80-47a4-aee7-22f506def104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='5658c99e-a891-4dc4-95e6-c38e4510642b']</value>
      <webElementGuid>0700709b-c16e-4176-83d9-762ebd76a88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ReimbursementTypeID_listbox']/li</value>
      <webElementGuid>fefb26b5-0de6-483f-b7ea-27b52386a23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='select'])[3]/following::li[1]</value>
      <webElementGuid>61484b9f-141a-49c5-b9d2-ec412b09048a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Type..'])[1]/following::li[1]</value>
      <webElementGuid>9b004dc5-54a1-4dfc-ad7d-f0a39df03c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tunjangan Khusus']/parent::*</value>
      <webElementGuid>fb4229ad-f1b2-47fe-83e1-5499b3b4f70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/ul/li</value>
      <webElementGuid>898f49bb-6359-4770-9f2c-a9517e31a293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '5658c99e-a891-4dc4-95e6-c38e4510642b' and (text() = 'Tunjangan Khusus' or . = 'Tunjangan Khusus')]</value>
      <webElementGuid>759b5c96-5f11-48c0-b784-3997d46e59dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
